name: Check service health

on:
  push:
    branches: feat/cronjob

jobs:
    check_health:
        runs-on: ubuntu-20.04
        environment: dev
        steps:
            - name: Check URL
              run: echo "test env var ${{ vars.APP_URL }}"
            - name: URL Health Check
              uses: Jtalk/url-health-check-action@v4
              with:
                url: ${{ vars.APP_URL }}
                follow-redirect: false
                max-attempts: 3
                retry-delay: 5s