name: Check service health

on:
  push:
    branches: feat/cronjob

jobs:
    check_health:
        runs-on: ubuntu-20.04
        steps:
            - name: Check URL
              run: echo "test env var ${{ vars.APP_URL }}"
        #   - name: URL Health Check
        #     uses: Jtalk/url-health-check-action@v4
        #     with:
        #       url: ${{ env.APP_URL }}
        #       run: echo "test env var ${{ env.APP_URL }}"
        