name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
      branches: [main]
      types: [opened, synchronize]

env:
  SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm run build
      - run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5001
      - if: ${{ github.event_name == 'push' && env.SKIP == 'false' }}
        name: deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: NOTIFY Deploy successful
        uses: stegzilla/discord-notify@v4
        if: ${{ env.SKIP == 'false' && success() }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: SUCCESS Deploy Pokedex
          message: "**Commit message:** ${{ join(github.event.commits.*.message) }} \n **URL** ${{ join(github.event.commits.*.url) }}"
      - name: NOTIFY Deploy failed
        uses: stegzilla/discord-notify@v4
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: FAILURE Deploy Pokedex
          message: "**Commit message:** ${{ join(github.event.commits.*.message) }} \n **URL** ${{ join(github.event.commits.*.url) }}"

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.event_name == 'push' && env.SKIP == 'false' }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
